### ISSUE TITLE
Predicate size? generates twice similar error message

### ISSUE THREAD

**Issue by jodosha** [dry-rb/dry-validation#121] opened 2016-05-02 11:19 UTC
```ruby
require 'bundler/setup'
require 'dry-validation'

schema = Dry::Validation.Schema do
  required(:foo) { size?(3) }
end

result = schema.call(foo: '')
puts result.messages.fetch(:foo).inspect

__END__

Expected:

  ['size must be 3']

Actual:

  ['length must be 3', 'size must be 3']
```

I'm using `master` at 2f2ab25b871dde41d4c0f2b259f0c09989f4176b.

**Comment by jodosha** [comment] 2016-05-02 12:06
A similar issue is caused by a range expectation (`size?(2..3)`). It returns:

```ruby
['length must be within 2 - 3', 'size must be within 2 - 3']
```

**Comment by fran-worley** [comment] 2016-06-06 17:19
Hints are incorrectly mapping to the message file:

```
require 'bundler/setup'
require 'dry-validation'

schema = Dry::Validation.Schema do
  required(:foo).filled(size?: 3)
end

result = schema.call(foo: '')
puts result.messages.fetch(:foo).inspect

__END__

Expected:

  ['must be filled', 'length must be 3']

Actual:

  ['must be filled', 'size must be 3']
```

**Comment by fran-worley** [comment] 2016-06-06 17:55
For consistency predicates `:max_size?` and `:min_size?` should probably also have a special message for strings.

**Comment by solnic** [comment] 2016-06-19 20:29
I'm gonna close this one in favor of the general issue #184

**Closed by solnic** 2016-06-19 20:29 UTC
Labels: bug

**Comment by solnic** [comment] 2016-06-21 09:55
OK so this is actually NOT a bug...hint compiler **does take into consideration value types** and this schema is missing a type predicate, if you add `int? & size?(2)` it's gonna be correct.

I'm gonna treat this as a poor UX though, it again goes back to detecting if type expectations are in place...adding explicit type-specs was step 1 towards improving this, now we gotta figure out a way of either enforcing type predicates or at least warning the user when a key is missing a type predicate.
