### ISSUE TITLE
'Dry::Container::Error - Nothing registered with the key ~';  type?: CustomClass

### ISSUE THREAD

**Issue by peco8** [dry-rb/dry-validation#306] opened 2017-01-11 05:42 UTC
I've been struggling to add custom class for validation.

```
class CreditCardUpdateForm
  include DryValidationForm

  Schema = Dry::Validation.Form do
    required(:account).value(type?: Account)
    required(:token).filled(:str?)
  end
end
```
This errors out 'Dry::Container::Error - Nothing registered with the key "account":'
Any ideas?

P.S This issue is related to https://github.com/dry-rb/dry-validation/issues/223

**Comment by solnic** [comment] 2017-01-11 10:45
Try `::Account` DSL context is an instance of `BasicObject` so constants must be provided with absolute paths

**Comment by peco8** [comment] 2017-01-11 11:54
@solnic 

Thanks for the answer.
Even I tried below;

```
class CreditCardUpdateForm
  include DryValidationForm

  Schema = Dry::Validation.Form do
    required(:account).value(type?: ::Account )
    required(:token).filled(:str?)
  end
end
```
I still get the same error...

**Comment by solnic** [comment] 2017-01-11 12:44
What's `DryValidationForm`?

**Comment by peco8** [comment] 2017-01-11 13:56
I use this library to check the parameters for service layer in rails.

```
#lib/dry_validation_form.rb
module DryValidationForm
  attr_reader :result

  class ValidationError < StandardError; end

  def initialize(params)
    @result = validate(before_validate(params))
  end

  def valid?
    result.success?
  end

  def validate!
    raise ValidationError, error_message if result.failure?
  end

  def attributes
    result.output
  end

  def errors
    result.messages(full: true).values.flatten
  end

  def error_message
    errors.join('. ')
  end

  private

  def before_validate(params)
    params.to_unsafe_hash # to_h if rals version is below 4.1
  end

  def validate(params)
    schema.call(params)
  end

  def schema
    self.class::Schema
  end
end
```

**Comment by solnic** [comment] 2017-01-11 13:57
Can you paste the backtrace?

**Comment by peco8** [comment] 2017-01-11 14:01
The turncated one is the following:

```
Dry::Container::Error - Nothing registered with the key "account":
  dry-container (0.6.0) lib/dry/container/resolver.rb:22:in `block in call'
  dry-container (0.6.0) lib/dry/container/resolver.rb:21:in `call'
  dry-container (0.6.0) lib/dry/container/mixin.rb:112:in `resolve'
  dry-container (0.6.0) lib/dry/container/mixin.rb:125:in `[]'
  dry-types (0.9.3) lib/dry/types.rb:82:in `block in []'
  concurrent-ruby (1.0.2) lib/concurrent/map.rb:133:in `block in fetch_or_store'
  concurrent-ruby (1.0.2) lib/concurrent/map.rb:122:in `fetch'
  concurrent-ruby (1.0.2) lib/concurrent/map.rb:132:in `fetch_or_store'
  dry-types (0.9.3) lib/dry/types.rb:73:in `[]'
  dry-types (0.9.3) lib/dry/types/compiler.rb:30:in `visit_type'
  dry-types (0.9.3) lib/dry/types/compiler.rb:15:in `visit'
  dry-types (0.9.3) lib/dry/types/compiler.rb:75:in `visit_key'
  dry-types (0.9.3) lib/dry/types/compiler.rb:15:in `visit'
  dry-types (0.9.3) lib/dry/types/compiler.rb:80:in `block in merge_with'
  dry-types (0.9.3) lib/dry/types/compiler.rb:80:in `merge_with'
  dry-types (0.9.3) lib/dry/types/compiler.rb:58:in `visit_form_hash'
  dry-types (0.9.3) lib/dry/types/compiler.rb:28:in `visit_type'
  dry-types (0.9.3) lib/dry/types/compiler.rb:15:in `visit'
  dry-types (0.9.3) lib/dry/types/compiler.rb:11:in `call'
  dry-validation (0.10.4) lib/dry/validation/input_processor_compiler.rb:16:in `call'
  dry-validation (0.10.4) lib/dry/validation/schema/deprecated.rb:14:in `input_processor'
  dry-validation (0.10.4) lib/dry/validation/schema/class_interface.rb:163:in `default_options'
  dry-validation (0.10.4) lib/dry/validation/schema/class_interface.rb:34:in `new'
  dry-validation (0.10.4) lib/dry/validation.rb:26:in `Schema'
  dry-validation (0.10.4) lib/dry/validation.rb:32:in `Form'
  app/forms/plan_create_form.rb:4:in `<class:PlanCreateForm>'
  app/forms/plan_create_form.rb:1:in `<top (required)>'
  activesupport (4.2.5.1) lib/active_support/dependencies.rb:457:in `block in load_file'
  activesupport (4.2.5.1) lib/active_support/dependencies.rb:647:in `new_constants_in'
  activesupport (4.2.5.1) lib/active_support/dependencies.rb:456:in `load_file'
  activesupport (4.2.5.1) lib/active_support/dependencies.rb:354:in `require_or_load'
  activesupport (4.2.5.1) lib/active_support/dependencies.rb:494:in `load_missing_constant'
  activesupport (4.2.5.1) lib/active_support/dependencies.rb:184:in `const_missing'
  activesupport (4.2.5.1) lib/active_support/dependencies.rb:526:in `load_missing_constant'
  activesupport (4.2.5.1) lib/active_support/dependencies.rb:184:in `const_missing'
  activesupport (4.2.5.1) lib/active_support/dependencies.rb:526:in `load_missing_constant'
  activesupport (4.2.5.1) lib/active_support/dependencies.rb:184:in `const_missing'
  activesupport (4.2.5.1) lib/active_support/dependencies.rb:526:in `load_missing_constant'
  activesupport (4.2.5.1) lib/active_support/dependencies.rb:184:in `const_missing'
  app/controllers/api/v1/plans_controller.rb:7:in `create'
  actionpack (4.2.5.1) lib/action_controller/metal/implicit_render.rb:4:in `send_action'
  actionpack (4.2.5.1) lib/abstract_controller/base.rb:198:in `process_action'
  actionpack (4.2.5.1) lib/action_controller/metal/rendering.rb:10:in `process_action'
  actionpack (4.2.5.1) lib/abstract_controller/callbacks.rb:20:in `block in process_action'
  activesupport (4.2.5.1) lib/active_support/callbacks.rb:117:in `call'
  activesupport (4.2.5.1) lib/active_support/callbacks.rb:555:in `block (2 levels) in compile'
  activesupport (4.2.5.1) lib/active_support/callbacks.rb:505:in `call'
  activesupport (4.2.5.1) lib/active_support/callbacks.rb:92:in `__run_callbacks__'
  activesupport (4.2.5.1) lib/active_support/callbacks.rb:778:in `_run_process_action_callbacks'
  activesupport (4.2.5.1) lib/active_support/callbacks.rb:81:in `run_callbacks'
  actionpack (4.2.5.1) lib/abstract_controller/callbacks.rb:19:in `process_action'
  actionpack (4.2.5.1) lib/action_controller/metal/rescue.rb:29:in `process_action'
  actionpack (4.2.5.1) lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
  activesupport (4.2.5.1) lib/active_support/notifications.rb:164:in `block in instrument'
  activesupport (4.2.5.1) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
  activesupport (4.2.5.1) lib/active_support/notifications.rb:164:in `instrument'
  actionpack (4.2.5.1) lib/action_controller/metal/instrumentation.rb:30:in `process_action'
  actionpack (4.2.5.1) lib/action_controller/metal/params_wrapper.rb:250:in `process_action'
  activerecord (4.2.5.1) lib/active_record/railties/controller_runtime.rb:18:in `process_action'
  actionpack (4.2.5.1) lib/abstract_controller/base.rb:137:in `process'
  actionview (4.2.5.1) lib/action_view/rendering.rb:30:in `process'
  actionpack (4.2.5.1) lib/action_controller/metal.rb:196:in `dispatch'
  actionpack (4.2.5.1) lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'
  actionpack (4.2.5.1) lib/action_controller/metal.rb:237:in `block in action'
  actionpack (4.2.5.1) lib/action_dispatch/routing/route_set.rb:74:in `dispatch'
  actionpack (4.2.5.1) lib/action_dispatch/routing/route_set.rb:43:in `serve'
  actionpack (4.2.5.1) lib/action_dispatch/journey/router.rb:43:in `block in serve'
  actionpack (4.2.5.1) lib/action_dispatch/journey/router.rb:30:in `serve'
  actionpack (4.2.5.1) lib/action_dispatch/routing/route_set.rb:815:in `call'
  rack (1.6.4) lib/rack/etag.rb:24:in `call'
  rack (1.6.4) lib/rack/conditionalget.rb:38:in `call'
  rack (1.6.4) lib/rack/head.rb:13:in `call'
  actionpack (4.2.5.1) lib/action_dispatch/middleware/params_parser.rb:27:in `call'
  app/middlewares/catch_json_parse_errors.rb:7:in `call'
  actionpack (4.2.5.1) lib/action_dispatch/middleware/flash.rb:260:in `call'
  rack (1.6.4) lib/rack/session/abstract/id.rb:225:in `context'
  rack (1.6.4) lib/rack/session/abstract/id.rb:220:in `call'
  actionpack (4.2.5.1) lib/action_dispatch/middleware/cookies.rb:560:in `call'
  activerecord (4.2.5.1) lib/active_record/query_cache.rb:36:in `call'
  activerecord (4.2.5.1) lib/active_record/connection_adapters/abstract/connection_pool.rb:653:in `call'
  activerecord (4.2.5.1) lib/active_record/migration.rb:377:in `call'
  actionpack (4.2.5.1) lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
  activesupport (4.2.5.1) lib/active_support/callbacks.rb:88:in `__run_callbacks__'
  activesupport (4.2.5.1) lib/active_support/callbacks.rb:778:in `_run_call_callbacks'
  activesupport (4.2.5.1) lib/active_support/callbacks.rb:81:in `run_callbacks'
  actionpack (4.2.5.1) lib/action_dispatch/middleware/callbacks.rb:27:in `call'
  actionpack (4.2.5.1) lib/action_dispatch/middleware/reloader.rb:73:in `call'
  actionpack (4.2.5.1) lib/action_dispatch/middleware/remote_ip.rb:78:in `call'
  better_errors (2.1.1) lib/better_errors/middleware.rb:84:in `protected_app_call'
  better_errors (2.1.1) lib/better_errors/middleware.rb:79:in `better_errors_call'
  better_errors (2.1.1) lib/better_errors/middleware.rb:57:in `call'
  actionpack (4.2.5.1) lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
  web-console (2.3.0) lib/web_console/middleware.rb:28:in `block in call'
  web-console (2.3.0) lib/web_console/middleware.rb:18:in `call'
  actionpack (4.2.5.1) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
  railties (4.2.5.1) lib/rails/rack/logger.rb:38:in `call_app'
  railties (4.2.5.1) lib/rails/rack/logger.rb:20:in `block in call'
  activesupport (4.2.5.1) lib/active_support/tagged_logging.rb:68:in `block in tagged'
  activesupport (4.2.5.1) lib/active_support/tagged_logging.rb:26:in `tagged'
  activesupport (4.2.5.1) lib/active_support/tagged_logging.rb:68:in `tagged'
  railties (4.2.5.1) lib/rails/rack/logger.rb:20:in `call'
  request_store (1.3.1) lib/request_store/middleware.rb:9:in `call'
  actionpack (4.2.5.1) lib/action_dispatch/middleware/request_id.rb:21:in `call'
  rack (1.6.4) lib/rack/methodoverride.rb:22:in `call'
  rack (1.6.4) lib/rack/runtime.rb:18:in `call'
  activesupport (4.2.5.1) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
  rack (1.6.4) lib/rack/lock.rb:17:in `call'
  actionpack (4.2.5.1) lib/action_dispatch/middleware/static.rb:116:in `call'
  rack (1.6.4) lib/rack/sendfile.rb:113:in `call'
  railties (4.2.5.1) lib/rails/engine.rb:518:in `call'
  railties (4.2.5.1) lib/rails/application.rb:165:in `call'
  rack (1.6.4) lib/rack/lock.rb:17:in `call'
  rack (1.6.4) lib/rack/content_length.rb:15:in `call'
  rack (1.6.4) lib/rack/handler/webrick.rb:88:in `service'
  /Users/toshikiinami/.rbenv/versions/2.3.1/lib/ruby/2.3.0/webrick/httpserver.rb:140:in `service'
  /Users/toshikiinami/.rbenv/versions/2.3.1/lib/ruby/2.3.0/webrick/httpserver.rb:96:in `run'
  /Users/toshikiinami/.rbenv/versions/2.3.1/lib/ruby/2.3.0/webrick/server.rb:296:in `block in start_thread'
```

**Comment by solnic** [comment] 2017-01-11 17:54
OK looks like #223 is still a problem

**Comment by solnic** [comment] 2017-01-11 17:55
Closing this as a duplicate of #223

**Closed by solnic** 2017-01-11 17:55 UTC
