### ISSUE TITLE
Dry::Validation.Form array `filled?` and `each` `int?` throwing an error

### ISSUE THREAD

**Issue by davebream** [dry-rb/dry-validation#175] opened 2016-06-06 09:49 UTC
With:
```ruby
Dry::Validation.Form do
  key(:name).required(:str?)
  key(:email).required(:str?)
  key(:price_ids) { filled? & each { int? } }
end
```

it throws error:
```
TypeError:
       no implicit conversion of Dry::Types::Definition into Hash
     # /bundle/gems/dry-types-0.7.2/lib/dry/types/compiler.rb:80:in `merge'
     # /bundle/gems/dry-types-0.7.2/lib/dry/types/compiler.rb:80:in `each'
     # /bundle/gems/dry-types-0.7.2/lib/dry/types/compiler.rb:80:in `reduce'
     # /bundle/gems/dry-types-0.7.2/lib/dry/types/compiler.rb:80:in `merge_with'
     # /bundle/gems/dry-types-0.7.2/lib/dry/types/compiler.rb:58:in `visit_form_hash'
     # /bundle/gems/dry-types-0.7.2/lib/dry/types/compiler.rb:28:in `visit_type'
     # /bundle/gems/dry-types-0.7.2/lib/dry/types/compiler.rb:15:in `visit'
     # /bundle/gems/dry-types-0.7.2/lib/dry/types/compiler.rb:75:in `visit_key'
     # /bundle/gems/dry-types-0.7.2/lib/dry/types/compiler.rb:15:in `visit'
     # /bundle/gems/dry-types-0.7.2/lib/dry/types/compiler.rb:80:in `block in merge_with'
     # /bundle/gems/dry-types-0.7.2/lib/dry/types/compiler.rb:80:in `map'
     # /bundle/gems/dry-types-0.7.2/lib/dry/types/compiler.rb:80:in `merge_with'
     # /bundle/gems/dry-types-0.7.2/lib/dry/types/compiler.rb:58:in `visit_form_hash'
     # /bundle/gems/dry-types-0.7.2/lib/dry/types/compiler.rb:28:in `visit_type'
     # /bundle/gems/dry-types-0.7.2/lib/dry/types/compiler.rb:15:in `visit'
     # /bundle/gems/dry-types-0.7.2/lib/dry/types/compiler.rb:11:in `call'
     # /bundle/gems/dry-validation-0.7.4/lib/dry/validation/input_processor_compiler.rb:16:in `call'
     # /bundle/gems/dry-validation-0.7.4/lib/dry/validation/schema.rb:123:in `input_processor'
     # /bundle/gems/dry-validation-0.7.4/lib/dry/validation/schema.rb:146:in `default_options'
     # /bundle/gems/dry-validation-0.7.4/lib/dry/validation/schema.rb:46:in `new'
     # /bundle/gems/dry-validation-0.7.4/lib/dry/validation.rb:37:in `Schema'
     # /bundle/gems/dry-validation-0.7.4/lib/dry/validation.rb:42:in `Form'
     # ./app/forms/api/v1/share_holidays_form.rb:34:in `schema'
     # ./app/forms/api/v1/share_holidays_form.rb:26:in `validate!'
     # ./app/forms/api/v1/share_holidays_form.rb:14:in `attributes'
     # ./spec/forms/api/v1/share_holidays_form_spec.rb:27:in `block (4 levels) in <top (required)>'
```

**Comment by fran-worley** [comment] 2016-06-06 17:36
I think that this is possibly a duplicate of https://github.com/dry-rb/dry-validation/issues/80

**Comment by solnic** [comment] 2016-06-06 17:39
I'll be working on an improved `each` macro that will allow you to set additional predicates for the value (not just members), although I don't have any concrete API ideas yet. Maybe sth like `required(:price_ids).each(:int?).min_size(2)` (this pretty much boils down to adding support for chaining, which is rather difficult, but I want to make it work regardless).

**Comment by solnic** [comment] 2016-07-01 07:50
This is now fixed in master.

**Comment by solnic** [comment] 2016-07-01 07:51
The improved syntax looks like this:

``` ruby
Dry::Validation.Form do
  required(:price_ids).filled { each(:int?) }
end
```

**Closed by solnic** 2016-07-01 07:50 UTC
Labels: bug
