### ISSUE TITLE
Validation ordering producing different error messages

### ISSUE THREAD

**Issue by backus** [dry-rb/dry-validation#145] opened 2016-05-07 00:12 UTC
It seems like, depending on how I order validations for an attribute, the messages `dry-validation` gives me vary:

```ruby
require 'dry/validation'

schema1 =
  Dry::Validation.Schema do
    required(:name) { filled? & str? & max_size?(2) }
  end

schema2 =
  Dry::Validation.Schema do
    required(:name) { filled? & max_size?(2) & str? }
  end

schema1.call({}).messages # => {:name=>["is missing", "size cannot be greater than 2"]}
schema2.call({}).messages # => {:name=>["is missing"]}
```

I would expect that either `"size cannot be greater than 2"` would show up in both outputs or neither. I also would expect that `"name must be a string"` would show up in both examples above given that dry-validation is supposed to generate all error messages if validation fails and short circuits.

**Comment by AMHOL** [comment] 2016-05-07 05:21
I've labelled this as a bug and discussion, logically I would think a type deceleration would come first, but perhaps we should infer this, one for Solnic

**Comment by solnic** [comment] 2016-05-07 10:41
Type expectations should be always defined first and hints do not include messages for type expectations, this is by design. We should somehow enforce it, which crossed my mind many times, as type expectations have much more meaning than other predicates and should be applied first.

Hints are being generated only for the right-side of conjunctions since when left-side fails you get a message from a predicate failure so there's no need to generate hints for that.

I wouldn't consider this to be a bug to be honest, this is expected behavior. The only issue is how the API works wrt type expectations. I feel like having a special interface for defining a type will be better. Ie `required(:name).type(:str).filled(max_size?: 2)`.

**Comment by solnic** [comment] 2016-05-07 10:43
ps. I'm gonna support dry-validation and respond to issues and clarify things despite my OSS holidays, esp that @jodosha is working on the integration so I don't want you guys to wait for my feedback for the whole month, I won't be doing any coding though so PRs are very welcome.

**Comment by solnic** [comment] 2016-09-05 22:40
This is now fixed in master

**Closed by solnic** 2016-09-05 22:40 UTC
Labels: discussion
